### ISSUE TITLE
'make clean' fails

### ISSUE THREAD

**Issue by enkiv2** [beastix/beastix#1]
Log:
[john@vonneumann beastix]$ make clean
make -C kernel/ mrproper
make[1]: Entering directory '/home/john/code/beastix/kernel'
make[1]: Leaving directory '/home/john/code/beastix/kernel'
make -C kernel/ clean O=../obj/kernel
make[1]: Entering directory '/home/john/code/beastix/kernel'
make[2]: Entering directory '/home/john/code/beastix/obj/kernel'
make[2]: Leaving directory '/home/john/code/beastix/obj/kernel'
make[1]: Leaving directory '/home/john/code/beastix/kernel'
make -i -C /home/john/code/beastix/bootstrap/binutils distclean clean
make[1]: Entering directory '/home/john/code/beastix/bootstrap/binutils'
make[1]: **\* No rule to make target 'distclean'.  Stop.
make[1]: Leaving directory '/home/john/code/beastix/bootstrap/binutils'
bootstrap/bootstrap.mk:58: recipe for target 'clean-bootstrap' failed
make: **\* [clean-bootstrap] Error 2

I'll fix this and produce a pull request.

**Comment by enkiv2** [comment]
Actually, this is an issue only if clean is called before binutils, gcc, etc are pulled down. Please mark as wontfix.

**Comment by GwenNelson** [comment]
You're correct, generally you should invoke the clean target with "make -i clean" like buildall.sh does
