### ISSUE TITLE
Multiple issues in build on xubuntu 

### ISSUE THREAD

**Issue by enkiv2** [beastix/beastix#2]
Log: https://gist.github.com/enkiv2/82711d924f5445ddfa48

Tail end:
syslex.c:1:1: warning: return type defaults to ‘int’ [-Wreturn-type]
syslex.c:1:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
gcc-4.7 -g -O2  -o sysinfo sysinfo.o syslex.o
syslex.o: In function `main':
/home/john/code/beastix/bootstrap/binutils/binutils/syslex.c:1: multiple definition of`main'
sysinfo.o:/home/john/code/beastix/bootstrap/binutils/binutils/sysinfo.c:1: first defined here
collect2: error: ld returned 1 exit status
make[3]: **\* [sysinfo] Error 1
make[3]: Leaving directory `/home/john/code/beastix/bootstrap/binutils/binutils'
make[2]: *** [all-binutils] Error 2
make[2]: Leaving directory`/home/john/code/beastix/bootstrap/binutils'
make[1]: **\* [all] Error 2
make[1]: Leaving directory `/home/john/code/beastix/bootstrap/binutils'
make: **\* [bootstrap-binutils] Error 2
mkdir -p /home/john/code/beastix/obj/headers
cp -Rv /home/john/code/beastix/bootstrap/tools/include/\* /home/john/code/beastix/obj/headers/
cp: cannot stat ‘/home/john/code/beastix/bootstrap/tools/include/_’: No such file or directory
make: *_\* [fixheaders] Error 1
mkdir -p /home/john/code/beastix/installer/_install
mkdir -p /home/john/code/beastix/installer/_install/bin
mkdir -p /home/john/code/beastix/installer/_install/etc
cp /home/john/code/beastix/installer/rc.local /home/john/code/beastix/installer/_install/etc/
cp /home/john/code/beastix/installer/installer_stage3.sh /home/john/code/beastix/installer/_install/bin/
~/code/beastix/releng ~/code/beastix
rm -rf /home/john/code/beastix/releng/../releng/build/*
rm -rf /home/john/code/beastix/releng/../releng/release/Beastix-0.1-CURRENT
mkdir /home/john/code/beastix/releng/../releng/release/Beastix-0.1-CURRENT
mkdir -p /home/john/code/beastix/releng/../releng/build/minroot
cp -R --preserve /home/john/code/beastix/releng/../world/rootfs/\*         /home/john/code/beastix/releng/../releng/build/minroot/
cp -R --preserve /home/john/code/beastix/releng/../obj/musl/_install/\*    /home/john/code/beastix/releng/../releng/build/minroot/
cp: cannot stat ‘/home/john/code/beastix/releng/../obj/musl/_install/_’: No such file or directory
make: *_\* [minimal-root] Error 1

**Comment by GwenNelson** [comment]
As stated in comments on the gist link, need "make buildkernel" before "make bootstrap" and the right gcc version - please confirm whether this is fixed (use 0.1-RELENG too) and close the issue or comment
