### ISSUE TITLE
Works on VirtualBox 5

### ISSUE THREAD

**Issue by ghost** [beastix/beastix#6]
On your homepage it says Beastix doesn't run under VirtualBox.

I've successfully booted Beastix-0.1-RELENG-14-Jun-2015.iso using VirtualBox 5.0.0 r101573 and a standard Linux VM configuration with 1 core available and 1024MB of RAM provided to the guest VM.

The DHCP script fails but that's probably a separate bug report.

**Comment by GwenNelson** [comment]
Hey

Thanks for the testing, as you can see development has slowed to a halt recently but will be picking up again.

Please do open another issue with the DHCP failure.
